name = "TRNC"
uuid = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
author = ["Robert Baraldi <rbaraldi@uw.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"


[compat]
julia = "^1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"

[targets]
test = ["Test", "TestSetExtensions"]