name = "RegularizedOptimization"
uuid = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
author = ["Robert Baraldi <rbaraldi@uw.edu> and Dominique Orban <dominique.orban@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RegularizedProblems = "ea076b23-609f-44d2-bb12-a4ae45328278"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
TSVD = "9449cd9e-2762-5aa3-a617-5413e99d722e"

[compat]
LinearOperators = "2.9"
NLPModels = "0.19, 0.20"
NLPModelsModifiers = "0.7"
Percival = "0.7.2"
ProximalOperators = "0.15"
RegularizedProblems = "0.1.1"
ShiftedProximalOperators = "0.2"
SolverCore = "0.3.0"
TSVD = "0.4"
julia = "^1.6.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizedProblems = "ea076b23-609f-44d2-bb12-a4ae45328278"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Random", "RegularizedProblems", "Test", "TestSetExtensions"]
