[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
TRNC = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
