[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RegularizedOptimization = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
RegularizedProblems = "ea076b23-609f-44d2-bb12-a4ae45328278"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"

[compat]
ADNLPModels = "0.4"
DifferentialEquations = "7"
MLDatasets = "0.7"
NLPModels = "0.19"
NLPModelsModifiers = "0.6"
PGFPlots = "3"
ProximalOperators = "0.15"
RegularizedOptimization = "0.1"
RegularizedProblems = "0.1"
ShiftedProximalOperators = "0.1"
